sudo: false
language: cpp
compiler: gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

git:
  depth: 1

branches:
  only:
    - master

# Make sure cmake picks up the compiler we want
install:
  - export CXX="g++-4.8" CC="gcc-4.8"

before_script:
    # Install desired version of ROOT
  - wget http://root.cern.ch/download/root_v5.34.30.source.tar.gz -P /tmp/
  - tar -xzf /tmp/root_v5.34.30.source.tar.gz
  - wget http://root.cern.ch/download/root_v5.34.30.Linux-ubuntu12-x86_64-gcc4.6.tar.gz -P /tmp/
  - tar -xzf /tmp/root_v5.34.30.Linux-ubuntu12-x86_64-gcc4.6.tar.gz
  - source ./root/bin/thisroot.sh
  - root-config --libs
  - root-config --cflags
    # Move some ROOT header files to common include directory
  - rsync -auv root/math/mathmore/inc/Math root/include/
    # Install dependencies
  - wget http://star-bnl.github.io/star-vertex/star-cvs_dev_12ae8226.tgz -P /tmp/
  - tar -xzf /tmp/star-cvs_dev_12ae8226.tgz
  - export STAR_ROOT_DIR="$PWD/star-cvs_dev_12ae8226"

script:
  - mkdir build/ && cd build/ && pwd
  - cmake -DSTAR_ROOT=$STAR_ROOT_DIR -DCMAKE_INSTALL_PREFIX=./ ../
  - make -j && make install && make clean
  - pwd && ls -la ./ && ls -la lib/
